### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by klazutin** [joshglendenning/win10-desktop-switcher#3]
I was enjoying the tool on Windows 10, unfortunately it stopped working after upgrading to Windows 11.
It now crashes with:
```
Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at DesktopSwitcher.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at DesktopSwitcher.Program.Main(String[] args)
```

**Comment by roel-v** [comment]
+1 from me. If you could document how to get the relevant GUIDs, I can look them up myself...

**Comment by roel-v** [comment]
In the mean time, this PowerShell script: https://www.powershellgallery.com/packages/VirtualDesktop works on various versions of Windows.

**Comment by isobit** [comment]
Hey folks, sorry it took so long to respond to this! Unfortunately I haven't used Windows as a daily driver for some time so I haven't been motivated to add support for Windows 11. Hopefully it is just a matter of finding new GUIDs but honestly I can't recall myself how I discovered them for Windows 10 as it's been so long. I'll do some cursory research, but also totally open to any contributions if anyone discovers how to add support for Windows 11.
