### ISSUE TITLE
Doesn't work on windows 11

### ISSUE THREAD

**Issue by roel-v** [joshglendenning/win10-desktop-switcher#4]
I know this tool is called 'win10-desktop-switcher', but it would be nice if it would also work on Windows 11. Seems to be a GUID issue like you mention, as the error message I get is 

Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at DesktopSwitcher.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at DesktopSwitcher.Program.Main(String[] args)

**Comment by roel-v** [comment]
Oops sorry just noticed someone else already reported this...
